using System.Text.Json.Serialization;

namespace VNeIDSignGateway.Models.Signing;

public class CertificateListRequest
{
    [JsonPropertyName("citizenPid")]
    public string CitizenPid { get; set; } = string.Empty;
}

public class CertificateListResponseData
{
    [JsonPropertyName("credentialIDs")]
    public List<string> CredentialIDs { get; set; } = new();

    [JsonPropertyName("credentialInfos")]
    public List<CredentialInfoItem> CredentialInfos { get; set; } = new();
}

public class CredentialInfoItem
{
    [JsonPropertyName("credentialID")]
    public string CredentialID { get; set; } = string.Empty;

    [JsonPropertyName("cert")]
    public CredentialCertDetail Cert { get; set; } = new();

    [JsonPropertyName("key")]
    public CredentialKeyDetail Key { get; set; } = new();
}

public class CredentialCertDetail
{
    /// <summary>
    /// 1: Active
    /// </summary>
    [JsonPropertyName("status")]
    public int Status { get; set; }

    /// <summary>
    /// Base64 X.509 cert chain: [end_entity, intermediate_ca, root_ca]
    /// </summary>
    [JsonPropertyName("certificates")]
    public List<string> Certificates { get; set; } = new();

    [JsonPropertyName("issuerDN")]
    public string? IssuerDN { get; set; }

    [JsonPropertyName("serialNumber")]
    public string? SerialNumber { get; set; }

    [JsonPropertyName("subjectDN")]
    public string? SubjectDN { get; set; }

    [JsonPropertyName("validFrom")]
    public string? ValidFrom { get; set; }

    [JsonPropertyName("validTo")]
    public string? ValidTo { get; set; }

    [JsonPropertyName("provider")]
    public string? Provider { get; set; }

    /// <summary>
    /// Authentication flow: 1 (via VNeID), 2 (via CCCD &amp; Face)
    /// </summary>
    [JsonPropertyName("flow")]
    public int Flow { get; set; }
}

public class CredentialKeyDetail
{
    [JsonPropertyName("status")]
    public string? Status { get; set; }

    /// <summary>
    /// Supported algorithm OIDs, e.g. ["1.2.840.113549.1.1.11"] (RSA with SHA256)
    /// </summary>
    [JsonPropertyName("algo")]
    public List<string> Algo { get; set; } = new();

    [JsonPropertyName("len")]
    public int Len { get; set; }

    [JsonPropertyName("curve")]
    public string? Curve { get; set; }
}

public class SignHashDocument
{
    [JsonPropertyName("documentName")]
    public string DocumentName { get; set; } = string.Empty;

    /// <summary>
    /// Cryptographic hash (digest) Base64 encoded (SHA-256)
    /// </summary>
    [JsonPropertyName("digestValue")]
    public string DigestValue { get; set; } = string.Empty;
}

public class SignHashRequest
{
    /// <summary>
    /// Selected credentialID / serialNumber
    /// </summary>
    [JsonPropertyName("credentialID")]
    public string CredentialID { get; set; } = string.Empty;

    /// <summary>
    /// Application code registered with Gateway
    /// </summary>
    [JsonPropertyName("originatorCode")]
    public string OriginatorCode { get; set; } = string.Empty;

    /// <summary>
    /// List of documents with digest hashes to sign
    /// </summary>
    [JsonPropertyName("documents")]
    public List<SignHashDocument> Documents { get; set; } = new();
}

public class SignHashResponseData
{
    /// <summary>
    /// Transaction handle generated by RS HUB
    /// </summary>
    [JsonPropertyName("handle")]
    public string Handle { get; set; } = string.Empty;

    /// <summary>
    /// Transaction expiration in seconds (default 300)
    /// </summary>
    [JsonPropertyName("expiresIn")]
    public int ExpiresIn { get; set; }

    /// <summary>
    /// CA Provider code
    /// </summary>
    [JsonPropertyName("provider")]
    public string? Provider { get; set; }
}

public class SignHashPollingRequest
{
    [JsonPropertyName("handle")]
    public string Handle { get; set; } = string.Empty;
}

public class SignHashPollingResponseData
{
    [JsonPropertyName("handle")]
    public string? Handle { get; set; }

    /// <summary>
    /// 0: Success, 1: Failed, 2: Processing, 3: Citizen rejected
    /// </summary>
    [JsonPropertyName("statusCode")]
    public int StatusCode { get; set; }

    [JsonPropertyName("resultCode")]
    public string? ResultCode { get; set; }

    [JsonPropertyName("errorCode")]
    public string? ErrorCode { get; set; }

    /// <summary>
    /// Array of Base64 signatures corresponding to digestValues
    /// </summary>
    [JsonPropertyName("signatures")]
    public List<string> Signatures { get; set; } = new();
}
