package com.rs.ca2.common

object IntentData {
    val KEY_BUSINESS_TYPE = "KEY_BUSINESS_TYPE"
    val KEY_MRZ_INFO = "KEY_MRZ_INFO"
    val KEY_PASSPORT = "KEY_PASSPORT"
    val KEY_FACE_LIVE = "KEY_FACE_LIVE"
    val KEY_VERIFY_ID_SUCCESS = "KEY_VERIFY_ID_SUCCESS"
    val KEY_LIVENESS_SUCCESS = "KEY_LIVENESS_SUCCESS"
    val KEY_CECA_ID_SUCCESS = "KEY_CECA_ID_SUCCESS"
    val KEY_FACE_MATCHING_SUCCESS = "KEY_FACE_MATCHING_SUCCESS"
    val KEY_TRANSACTION_TYPE_C = "KEY_TRANSACTION_TYPE_C"
    val KEY_OTP_TYPE = "KEY_OTP_TYPE"
    val KEY_TRANSACTION_STATUS = "KEY_TRANSACTION_STATUS"
    val KEY_QRCODE_INFO = "KEY_QR_CODE_RESULT"
}
