package com.rs.ca2.common

object PreferencesKeys {
    val KEY_SHARE_NAME = "X_DEMOAPP"


    val KEY_OCR_ENGINE_MODE = "KEY_OCR_ENGINE_MODE"
    val KEY_CONTINUOUS_PREVIEW = "KEY_CONTINUOUS_PREVIEW"
    val KEY_ID_CARD = "KEY_CONTINUOUS_PREVIEW"
    val KEY_CHIP_IMAGE = "KEY_CHIP_IMAGE"
    val KEY_ONBOARD_IMAGE = "KEY_ONBOARD_IMAGE"
    val KEY_EID = "KEY_EID"


}
