require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'CA2RemoteSignning' do
  use_expo_modules!
  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'npx',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end
  pod 'Alamofire', '~> 5.10.2'
  pod 'OpenSSL-Universal', '~> 3.1.6000'
  pod 'CocoaLumberjack/Swift'
  pod 'ObjectMapper'
  pod 'SwiftDate'
  pod 'PINCache'
  pod 'PINOperation'
  pod 'OTPFieldView'
  pod 'DZNEmptyDataSet'
  pod 'TPKeyboardAvoiding'
  pod 'DifferenceKit'
  pod 'SnapKit'
  pod 'PanModal'
  pod 'iProgressHUD'
  pod 'FCAlertView'
  pod 'SwiftMessages'
  pod 'lottie-ios'
  pod 'HMSegmentedControl'
  pod 'SwiftyJSON'
  pod 'ImageSlideshow', '~> 1.9.0'
  pod "ImageSlideshow/Alamofire"
  config = use_native_modules!(config_command)
  # use_frameworks! :linkage => :dynamic, :pods => ['Alamofire', 'ImageSlideshow/Alamofire']
  # use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  # use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']
  use_frameworks! :linkage => :dynamic
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('RNReanimated')
        def pod.build_type
          Pod::BuildType.static_library
        end
      end
     end
   end
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )
    installer.pods_project.targets.each do |target|
      # Danh sách các pod cần cấu hình
      configured_pods = [
        'Alamofire',
        'AlamofireImage',
        'OpenSSL-Universal',
        'CocoaLumberjack',
        'CocoaLumberjack-Static',
        'ObjectMapper',
        'SwiftDate',
        'PINCache',
        'PINOperation',
        'OTPFieldView',
        'DZNEmptyDataSet',
        'TPKeyboardAvoiding',
        'DifferenceKit',
        'SnapKit',
        'PanModal',
        'iProgressHUD',
        'FCAlertView',
        'SwiftMessages',
        'lottie-ios',
        'HMSegmentedControl',
        'SwiftyJSON',
        'ImageSlideshow',
        'ImageSlideshow-Alamofire'
      ]

      installer.pods_project.targets.each do |target|
        if target.name == 'Alamofire'
          target.build_configurations.each do |config|
            config.build_settings['VALIDATE_SWIFT_MODULES'] = 'NO'
          end
        end
      end
      if configured_pods.include?(target.name)
        target.build_configurations.each do |config|
          #config.build_settings['SWIFT_VERSION'] = '6.0'
          #config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'targeted'  # hoặc 'minimal'
          config.build_settings['LD_NO_PIE'] = 'NO'
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
          config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
          config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    
          xcconfig_path = config.base_configuration_reference.real_path
          if File.exist?(xcconfig_path)
            xcconfig = File.read(xcconfig_path)
            xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
            File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
          end
        end
      end
    end
    
    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
