import Expo
import FirebaseCore
import React
import ReactAppDependencyProvider
import UIKit
@_exported import xverifysdk

let APPDELEGATE = UIApplication.shared.delegate as! AppDelegate

@UIApplicationMain
public class AppDelegate: ExpoAppDelegate {
    var window: UIWindow?

    var reactNativeDelegate: ExpoReactNativeFactoryDelegate?
    var reactNativeFactory: RCTReactNativeFactory?

    public override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
    ) -> Bool {
        // Expo React Native initialization
        let delegate = ReactNativeDelegate()
        let factory = ExpoReactNativeFactory(delegate: delegate)
        delegate.dependencyProvider = RCTAppDependencyProvider()

        reactNativeDelegate = delegate
        reactNativeFactory = factory
        bindReactNativeFactory(factory)

        #if os(iOS) || os(tvOS)
        window = UIWindow(frame: UIScreen.main.bounds)
        // Firebase configuration (generated by Expo prebuild)
        FirebaseApp.configure()
        factory.startReactNative(
            withModuleName: "main",
            in: window,
            launchOptions: launchOptions
        )
        #endif

        // Your custom logic
        print("\n/////////////////////////////////////////////////////////////////////////////////////")
        print("* \(APP.debugInfo)")
        print("* Home directory: \(APP.baseUrl.path)")
        print("\n/////////////////////////////////////////////////////////////////////////////////////")

        // Initializations for xverifysdk
        ONBOARDDATAMANAGER.eidNumber = UserDefaults.standard.string(forKey: "eidNumber")
        if let imagePath = UserDefaults.standard.string(forKey: "chipImage") {
            ONBOARDDATAMANAGER.bioEidChipImagePath = imagePath
        }
        if let faceImagePath = UserDefaults.standard.string(forKey: "onboardFace") {
            ONBOARDDATAMANAGER.bioImageOnboard = faceImagePath
        }

        do {
            if let data = UserDefaults.standard.data(forKey: "eidData") {
                let res = try JSONDecoder().decode(RarVerificationRequestModel.self, from: data)
                ONBOARDDATAMANAGER.eidBio = res
            } else {
                Log.error("No data")
            }
        } catch {
            print(error)
        }

        // Theme and API initialization
        BrandManager.setDefaultTheme()
        //registerLocal()

        let apiKey = Bundle.main.infoDictionary?["API_KEY"] as! String
        let baseUrl = Bundle.main.infoDictionary?["API_BASE_URL"] as! String
        let customerCode = Bundle.main.infoDictionary?["CUSTOMER_CODE"] as! String
        let bioBaseUrl = Bundle.main.infoDictionary?["API_BIO2345_BASE_URL"] as! String

        APISERVICE.initialize(apiKey: apiKey, apiBaseUrl: baseUrl, customerCode: customerCode)
        BIOAPISERVICE.initialize(apiKey: apiKey, apiBaseUrl: bioBaseUrl, customerCode: customerCode)

        // Fix header padding
        if #available(iOS 15.0, *) {
            UITableView.appearance().sectionHeaderTopPadding = 0.0
        }

        // Check onboard status
        BIOFACADE.bioGetOnboardStatus(deviceUUID: Utils.sampleDeviceUUID) { status in
            ONBOARDDATAMANAGER.onboardStatus = status
        } onError: { error in
            Log.error(error.localizedDescription)
        }

        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }

    // Linking API
    public override func application(
        _ app: UIApplication,
        open url: URL,
        options: [UIApplication.OpenURLOptionsKey: Any] = [:]
    ) -> Bool {
        return super.application(app, open: url, options: options) || RCTLinkingManager.application(app, open: url, options: options)
    }

    // Universal Links
    public override func application(
        _ application: UIApplication,
        continue userActivity: NSUserActivity,
        restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void
    ) -> Bool {
        let result = RCTLinkingManager.application(application, continue: userActivity, restorationHandler: restorationHandler)
        return super.application(application, continue: userActivity, restorationHandler: restorationHandler) || result
    }

    // Custom method to setup root controller
    func setupRootController(_ controller: UIViewController, _ isHiddenNavigationBar: Bool = false) {
        let navController = NavigationController(rootViewController: controller)
        navController.setNavigationBarHidden(isHiddenNavigationBar, animated: false)
        let window = UIWindow(frame: UIScreen.main.bounds)
        APP.window = window
        window.overrideUserInterfaceStyle = .light
        window.backgroundColor = ColorBrand.appColorBackground
        window.rootViewController = navController
        window.makeKeyAndVisible()
    }

    // Local notification registration
    func registerLocal() {
        let center = UNUserNotificationCenter.current()
        center.requestAuthorization(options: [.alert, .badge, .sound]) { (success, error) in
            if success {
                print("Notification authorization success")
            } else {
                print("Notification authorization failed: \(error?.localizedDescription ?? "Unknown error")")
            }
        }
    }
}

// ReactNativeDelegate for Expo
class ReactNativeDelegate: ExpoReactNativeFactoryDelegate {
    override func sourceURL(for bridge: RCTBridge) -> URL? {
        bridge.bundleURL ?? bundleURL()
    }

    override func bundleURL() -> URL? {
        #if DEBUG
        return RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: ".expo/.virtual-metro-entry")
        #else
        return Bundle.main.url(forResource: "main", withExtension: "jsbundle")
        #endif
    }
}
